spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenges_db
    username: root
    password:

  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      bindings:
        usersTopicConsumer-in-0:
          destination: usersTopic
          group: chal-group
        function:
          definition: usersTopicConsumer