
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: root
    password:
  cloud:
    stream:
      bindings:
        usersTopicConsumer-in-0:
          destination: usersTopic
          group: notif-group
        notificationsTopic-out-0:
          destination: notificationsTopic
          content-type: application/json
        function:
          definition: usersTopicConsumer , usersTopic
