spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
    password:

  kafka:
    bootstrap-servers: localhost:9092  # Adresse et port de votre serveur Kafka
    producer:
      client-id: transaction-producer  # (Optionnel) Nom du client Kafka pour cette application

  cloud:
    stream:
      bindings:
        output-out-0:
          destination: transactionsTopic  # Topic pour produire les messages
          content-type: application/json   # Sérialisation en JSON
        usersTopicConsumer-in-0:
          destination: usersTopic         # Topic à consommer
          content-type: application/json

      function:
        definition: usersTopicConsumer  # Fonction qui consomme les messages
        bindings:
          usersTopicConsumer-in-0:
            destination: usersTopic
            content-type: application/json

      kafka:
        binder:
          producer-properties:
            retries: 3
            acks: all
            compression-type: gzip
