spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
    password:

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: transaction-producer

  cloud:
    stream:
      bindings:
        usersTopicConsumer-in-0:
          destination: usersTopic
          content-type: application/json
      function:
        definition: usersTopicConsumer
      kafka:
        binder:
          producer-properties:
            retries: 3
            acks: all
            compression-type: gzip