spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password:

  kafka:
    bootstrap-servers: localhost:9092  # Adresse et port de votre serveur Kafka
    producer:
      client-id: auth-producer  # (Optionnel) Nom du client Kafka pour cette application

  cloud:
    stream:
      bindings:
        output-out-0:
          destination : usersTopic

